CREATE TABLE `suppliers` (
	`SupplierID` INT(10) NOT NULL,
	`SupplierName` VARCHAR(30) NOT NULL COLLATE,
	`ContactName` VARCHAR(20) NOT NULL COLLATE,
	`Address` VARCHAR(30) NOT NULL COLLATE,
	`City` VARCHAR(15) NOT NULL COLLATE,
	`PostalCode` VARCHAR(15) NOT NULL,
	`Country` VARCHAR(15) NOT NULL,
	PRIMARY KEY (`SupplierID`) USING BTREE
);
