CREATE TABLE `customer` (
`CUST_ID` INT(10) NOT NULL,
`CUST_NAME` VARCHAR(30) NOT NULL,
`ANN_REV` DECIMAL(10,2) NOT NULL,
`CUST_TYPE` VARCHAR(20) NOT NULL,
PRIMARY KEY (`CUST_ID`) USING BTREE,
CONSTRAINT `CC2` CHECK ((`CUST_TYPE` IN
('MANUFACTURER',’WHOLESALER','RETAILER'))),
CONSTRAINT `CC1` CHECK (((`CUST_ID` >= 100) AND (`CUST_ID` <= 1000)))
);
