CREATE TABLE `shipment` (
`SHIPMENT_NO` INT(10) NOT NULL,
`CUST_ID` INT(10) NOT NULL,
`WEIGHT` DECIMAL(15,2) NOT NULL,
`TRUCK_NO` INT(10) NOT NULL,
`DESTINATION` VARCHAR(25) NOT NULL,
`SHIP_DATE` DATE NOT NULL,

PRIMARY KEY (`SHIPMENT_NO`,`CUST_ID`) USING BTREE,
INDEX `FK__customer` (`CUST_ID`) USING BTREE,
INDEX `FK__truck` (`TRUCK_NO`) USING BTREE,
INDEX `FK__city` (`DESTINATION`) USING BTREE,

CONSTRAINT `FK__city` FOREIGN KEY (`DESTINATION`) REFERENCES
`shipping`.`city` (`CITY_NAME`) ON UPDATE NO ACTION ON DELETE NO ACTION,
CONSTRAINT `FK__customer` FOREIGN KEY (`CUST_ID`) REFERENCES
`shipping`.`customer` (`CUST_ID`) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT `FK__truck` FOREIGN KEY (`TRUCK_NO`) REFERENCES
`shipping`.`truck` (`TRUCK_NO`) ON UPDATE NO ACTION ON DELETE NO ACTION,
CONSTRAINT `CS1` CHECK ((`WEIGHT` < 1000))
);
