INSERT INTO `shipping`.customer VALUES(101,'MICHAEL GOUGH',500.0,'MANUFACTURER');

INSERT INTO `shipping`.customer VALUES(102,'TOM BLUNDELL',300.5,'MANUFACTURER');

INSERT INTO `shipping`.customer VALUES(103,'ANDY CADDICK',150.0,'RETAILER');

INSERT INTO `shipping`.customer VALUES(104,'ASHLEY GILES',200.0,'WHOLESALER');

INSERT INTO `shipping`.customer VALUES(105,'JOSEPH BURNS',500.0,'MANUFACTURER');

INSERT INTO `shipping`.customer VALUES(106,'MARK NICHOLAS',425.5,'WHOLESALER');

INSERT INTO `shipping`.customer VALUES(107,'TIM SEIFERT',100.0,'RETAILER');

INSERT INTO `shipping`.customer VALUES(108,'DEAN ELGAR',190.0,'WHOLESALER');