CREATE TABLE `customers` (
	`CNO` INT(10) NOT NULL,
	`CNAME` VARCHAR(30) NOT NULL,
	`STREET` VARCHAR(40) NOT NULL,
	`ZIP` INT(10) NOT NULL,
	`PHONE` VARCHAR(12) NOT NULL,
	PRIMARY KEY (`CNO`) USING BTREE,
	INDEX `FK__zipcodes_2` (`ZIP`) USING BTREE,
	CONSTRAINT `FK__zipcodes_2` FOREIGN KEY (`ZIP`) REFERENCES `mail-order`.`zipcodes` (`ZIP`) ON UPDATE NO ACTION ON DELETE NO ACTION
);
