CREATE TABLE `orders` (
	`ONO` INT(10) NOT NULL,
	`CNO` INT(10) NOT NULL,
	`ENO` INT(10) NOT NULL,
	`PRECEIVED` DATE NULL DEFAULT NULL,
	`SHIPPED` DATE NULL DEFAULT NULL,
	PRIMARY KEY (`ONO`) USING BTREE,
	INDEX `FK__customers` (`CNO`) USING BTREE,
	INDEX `FK__employees` (`ENO`) USING BTREE,
	CONSTRAINT `FK__customers` FOREIGN KEY (`CNO`) REFERENCES `mail-order`.`customers` (`CNO`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK__employees` FOREIGN KEY (`ENO`) REFERENCES `mail-order`.`employees` (`ENO`) ON UPDATE NO ACTION ON DELETE NO ACTION

);
