CREATE TABLE `employees` (
	`ENO` INT(10) NOT NULL,
	`ENAME` VARCHAR(30) NOT NULL,
	`ZIP` INT(10) NOT NULL,
	`HDATE` DATE NOT NULL,
	PRIMARY KEY (`ENO`) USING BTREE,
	INDEX `FK__zipcodes` (`ZIP`) USING BTREE,

	CONSTRAINT `FK__zipcodes` FOREIGN KEY (`ZIP`) REFERENCES `mail-order`.`zipcodes` (`ZIP`) ON UPDATE NO ACTION ON DELETE NO ACTION
);
