CREATE TABLE `orders` (
`ORD_NO` INT(10) NOT NULL,
`PURCHASE_AMT` DECIMAL(10,2) NOT NULL,
`ORD_DATE` DATE NOT NULL,
`CUSTOMER_ID` INT(10) NOT NULL,
`SALESMAN_ID` INT(10) NOT NULL,
PRIMARY KEY (`ORD_NO`) USING BTREE,
INDEX `FK2` (`CUSTOMER_ID`) USING BTREE,
INDEX `FK2__salesman` (`SALESMAN_ID`) USING BTREE,
CONSTRAINT `FK2` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES
`order`.`customer` (`CUSTOMER_ID`) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT `FK2__salesman` FOREIGN KEY (`SALESMAN_ID`) REFERENCES
`order`.`salesman` (`SALESMAN_ID`) ON UPDATE CASCADE ON DELETE CASCADE
);
