CREATE TABLE `rating` (
`MOV_ID` INT(10) NOT NULL,
`REV_STARS` INT(10) NOT NULL,
PRIMARY KEY (`MOV_ID`) USING BTREE,
CONSTRAINT `FK2` FOREIGN KEY (`MOV_ID`) REFERENCES `movie`.`movies`
(`MOV_ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
);
