CREATE TABLE `movie_cast` (
`ACT_ID` INT(10) NOT NULL,
`MOV_ID` INT(10) NOT NULL,
`ROLE` VARCHAR(15) NOT NULL,
PRIMARY KEY (`ACT_ID`, `MOV_ID`) USING BTREE,
INDEX `FK__movies` (`MOV_ID`) USING BTREE,
CONSTRAINT `FK__actor` FOREIGN KEY (`ACT_ID`) REFERENCES
`movie`.`actor` (`ACT_ID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
CONSTRAINT `FK__movies` FOREIGN KEY (`MOV_ID`) REFERENCES
`movie`.`movies` (`MOV_ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
);
