CREATE TABLE `movies` (
`MOV_ID` INT(10) NOT NULL,
`MOV_TITLE` VARCHAR(25) NOT NULL,
`MOV_YEAR` INT(10) NOT NULL,
`MOV_LANG` VARCHAR(12) NOT NULL,
`DIR_ID` INT(10) NOT NULL,
PRIMARY KEY (`MOV_ID`) USING BTREE,
INDEX `FK__director` (`DIR_ID`) USING BTREE,
CONSTRAINT `FK__director` FOREIGN KEY (`DIR_ID`) REFERENCES
`movie`.`director` (`DIR_ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
);
